# Generated by Django 5.1.3 on 2024-12-29 02:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media/gallery_images/')),
                ('grid_column_span', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('grid_row_span', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
