# Generated by Django 5.1.4 on 2024-12-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_survey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_survey', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='freecomment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='number_survey',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='freecomment',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system_survey_app.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_survey_app.survey'),
            preserve_default=False,
        ),
    ]
