# Generated by Django 5.1.4 on 2024-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_survey_app', '0002_survey_remove_freecomment_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
