# Generated by Django 5.1.3 on 2024-12-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('type', models.CharField(choices=[('LINK', 'link'), ('VIDEO', 'video'), ('FILE', 'file'), ('IMAGE', 'image')], default='LINK', max_length=20)),
            ],
        ),
    ]
