# Generated by Django 5.1.3 on 2024-12-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
