# Generated by Django 5.1.4 on 2024-12-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='title', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
