# Generated by Django 5.1.3 on 2024-12-21 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0002_theme_note_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='diary_app.theme'),
        ),
    ]
