# Generated by Django 5.1.3 on 2024-12-14 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('author', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_author', to=settings.AUTH_USER_MODEL)),
                ('related_section', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='section_theme', to='forum_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('message_author', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_author', to=settings.AUTH_USER_MODEL)),
                ('related_theme', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theme_message', to='forum_app.theme')),
            ],
        ),
    ]
