# Generated by Django 5.1.3 on 2024-12-29 02:24

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('tag', models.CharField(blank=True, max_length=10)),
                ('tag_color', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('tag', models.CharField(blank=True, max_length=10)),
                ('tag_color', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_author', to=settings.AUTH_USER_MODEL)),
                ('related_section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_theme', to='forum_app.section')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='forum_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.theme')),
            ],
        ),
    ]
